[package]
name = "rtdownloader"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
#tokio = { version = "1.39.2", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_bencode = "0.2.4"
serde_bytes = "0.11.15"
serde_derive = "1.0.208"
sha-1 = "0.10.1"
